// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace WorkOrderManagement.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "WorkOrderManagement")]
    [global::Xunit.TraitAttribute("Category", "DemandeIntervention")]
    public partial class DeclarationDuneDemandeDinterventionSurUnEquipementFeature : object, global::Xunit.IClassFixture<DeclarationDuneDemandeDinterventionSurUnEquipementFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "WorkOrderManagement",
                "DemandeIntervention"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("fr"), "Features", "Déclaration d\'une demande d\'intervention sur un équipement", "    En tant que technicien ayant scanné le QR Code d\'un équipement\r\n    Je veux d" +
                "éclarer une demande d\'intervention pour signaler une panne\r\n    Afin que la main" +
                "tenance soit planifiée et tracée", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "DeclarationDemandeIntervention.feature"
#line hidden
        
        public DeclarationDuneDemandeDinterventionSurUnEquipementFeature(DeclarationDuneDemandeDinterventionSurUnEquipementFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
    #line hidden
            global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                        "Identifiant",
                        "Tag",
                        "Désignation",
                        "Localisation",
                        "Statut"});
            table1.AddRow(new string[] {
                        "3f2504e0-4f89-41d3-9a0c-0305e82c3301",
                        "CTA-A1-002",
                        "Centrale Traitement d\'Air",
                        "Site Lyon - Bât. A - Toiture",
                        "Actif"});
            table1.AddRow(new string[] {
                        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
                        "ASC-B2-007",
                        "Ascenseur passagers",
                        "Site Lyon - Bât. B - Niveau 2",
                        "Déposé"});
#line 9
        await testRunner.GivenAsync("le catalogue d\'assets exposé par AssetManagement", ((string)(null)), table1, "Étant donné ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/DeclarationDemandeIntervention.feature.ndjson", 6);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Déclaration réussie d\'une panne sur un équipement actif")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Déclaration d\'une demande d\'intervention sur un équipement")]
        [global::Xunit.TraitAttribute("Description", "Déclaration réussie d\'une panne sur un équipement actif")]
        public async global::System.Threading.Tasks.Task DeclarationReussieDunePanneSurUnEquipementActif()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Déclaration réussie d\'une panne sur un équipement actif", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 15
        await testRunner.GivenAsync("l\'équipement résolu d\'identifiant \"3f2504e0-4f89-41d3-9a0c-0305e82c3301\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Étant donné ");
#line hidden
#line 16
        await testRunner.WhenAsync("le technicien \"j.martin\" déclare une panne \"Arrêt complet de la CTA, plus de souf" +
                        "flage\" en priorité \"Critique\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quand ");
#line hidden
#line 17
        await testRunner.ThenAsync("une demande d\'intervention est créée", ((string)(null)), ((global::Reqnroll.Table)(null)), "Alors ");
#line hidden
#line 18
        await testRunner.AndAsync("la demande référence l\'équipement \"CTA-A1-002 - Centrale Traitement d\'Air\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Et ");
#line hidden
#line 19
        await testRunner.AndAsync("la demande est en priorité \"Critique\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Et ");
#line hidden
#line 20
        await testRunner.AndAsync("la demande est déclarée par \"j.martin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Et ");
#line hidden
#line 21
        await testRunner.AndAsync("la demande est au statut \"Soumise\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Et ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Refus de déclaration sur un équipement déposé")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Déclaration d\'une demande d\'intervention sur un équipement")]
        [global::Xunit.TraitAttribute("Description", "Refus de déclaration sur un équipement déposé")]
        public async global::System.Threading.Tasks.Task RefusDeDeclarationSurUnEquipementDepose()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Refus de déclaration sur un équipement déposé", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 24
        await testRunner.GivenAsync("l\'équipement résolu d\'identifiant \"7c9e6679-7425-40de-944b-e07fc1f90ae7\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Étant donné ");
#line hidden
#line 25
        await testRunner.WhenAsync("le technicien \"j.martin\" déclare une panne \"Porte bloquée\" en priorité \"Normale\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quand ");
#line hidden
#line 26
        await testRunner.ThenAsync("aucune demande d\'intervention n\'est créée", ((string)(null)), ((global::Reqnroll.Table)(null)), "Alors ");
#line hidden
#line 27
        await testRunner.AndAsync("la déclaration est refusée avec le motif \"Équipement non éligible\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Et ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Refus de déclaration pour un équipement inconnu du catalogue")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Déclaration d\'une demande d\'intervention sur un équipement")]
        [global::Xunit.TraitAttribute("Description", "Refus de déclaration pour un équipement inconnu du catalogue")]
        public async global::System.Threading.Tasks.Task RefusDeDeclarationPourUnEquipementInconnuDuCatalogue()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Refus de déclaration pour un équipement inconnu du catalogue", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 29
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 30
        await testRunner.GivenAsync("l\'équipement résolu d\'identifiant \"00000000-0000-0000-0000-000000000099\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Étant donné ");
#line hidden
#line 31
        await testRunner.WhenAsync("le technicien \"j.martin\" déclare une panne \"Bruit anormal\" en priorité \"Normale\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quand ");
#line hidden
#line 32
        await testRunner.ThenAsync("aucune demande d\'intervention n\'est créée", ((string)(null)), ((global::Reqnroll.Table)(null)), "Alors ");
#line hidden
#line 33
        await testRunner.AndAsync("la déclaration est refusée avec le motif \"Équipement non éligible\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Et ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Refus de déclaration sans description de panne")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Déclaration d\'une demande d\'intervention sur un équipement")]
        [global::Xunit.TraitAttribute("Description", "Refus de déclaration sans description de panne")]
        public async global::System.Threading.Tasks.Task RefusDeDeclarationSansDescriptionDePanne()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Refus de déclaration sans description de panne", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 35
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 36
        await testRunner.GivenAsync("l\'équipement résolu d\'identifiant \"3f2504e0-4f89-41d3-9a0c-0305e82c3301\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Étant donné ");
#line hidden
#line 37
        await testRunner.WhenAsync("le technicien \"j.martin\" déclare une panne \"\" en priorité \"Normale\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quand ");
#line hidden
#line 38
        await testRunner.ThenAsync("aucune demande d\'intervention n\'est créée", ((string)(null)), ((global::Reqnroll.Table)(null)), "Alors ");
#line hidden
#line 39
        await testRunner.AndAsync("la déclaration est refusée avec le motif \"Signalement invalide\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Et ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await DeclarationDuneDemandeDinterventionSurUnEquipementFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await DeclarationDuneDemandeDinterventionSurUnEquipementFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
