// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace AssetManagement.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Interprétation d\'un QR Code d\'équipement")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("AssetManagement")]
    [global::NUnit.Framework.CategoryAttribute("QrCode")]
    public partial class InterpretationDunQRCodeDequipementFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "AssetManagement",
                "QrCode"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("fr"), "Features", "Interprétation d\'un QR Code d\'équipement", "    En tant que technicien de maintenance en intervention sur le terrain\r\n    Je " +
                "veux scanner le QR Code apposé sur un équipement\r\n    Afin d\'identifier de façon" +
                " fiable l\'asset concerné avant toute déclaration", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "InterpretationQrCode.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
    #line hidden
            global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                        "Identifiant",
                        "Tag",
                        "Désignation",
                        "Localisation",
                        "Statut"});
            table1.AddRow(new string[] {
                        "3f2504e0-4f89-41d3-9a0c-0305e82c3301",
                        "CTA-A1-002",
                        "Centrale Traitement d\'Air",
                        "Site Lyon - Bât. A - Toiture",
                        "Actif"});
            table1.AddRow(new string[] {
                        "7c9e6679-7425-40de-944b-e07fc1f90ae7",
                        "ASC-B2-007",
                        "Ascenseur passagers",
                        "Site Lyon - Bât. B - Niveau 2",
                        "Déposé"});
#line 9
        await testRunner.GivenAsync("le référentiel d\'assets suivant", ((string)(null)), table1, "Étant donné ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/InterpretationQrCode.feature.ndjson", 11);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Scan d\'un QR Code valide pointant vers un équipement actif")]
        public async global::System.Threading.Tasks.Task ScanDunQRCodeValidePointantVersUnEquipementActif()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Scan d\'un QR Code valide pointant vers un équipement actif", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 15
        await testRunner.GivenAsync("un QR Code encodant l\'URL \"https://gmao.exemple.fr/assets/3f2504e0-4f89-41d3-9a0c" +
                        "-0305e82c3301\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Étant donné ");
#line hidden
#line 16
        await testRunner.WhenAsync("le technicien scanne le QR Code", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quand ");
#line hidden
#line 17
        await testRunner.ThenAsync("le QR Code est résolu avec succès", ((string)(null)), ((global::Reqnroll.Table)(null)), "Alors ");
#line hidden
#line 18
        await testRunner.AndAsync("l\'équipement identifié porte le tag \"CTA-A1-002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Et ");
#line hidden
#line 19
        await testRunner.AndAsync("l\'équipement identifié est situé à \"Site Lyon - Bât. A - Toiture\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Et ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Scan d\'un contenu qui n\'est pas une URL exploitable")]
        public async global::System.Threading.Tasks.Task ScanDunContenuQuiNestPasUneURLExploitable()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Scan d\'un contenu qui n\'est pas une URL exploitable", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 21
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 22
        await testRunner.GivenAsync("un QR Code encodant l\'URL \"ceci-n-est-pas-une-url\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Étant donné ");
#line hidden
#line 23
        await testRunner.WhenAsync("le technicien scanne le QR Code", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quand ");
#line hidden
#line 24
        await testRunner.ThenAsync("l\'interprétation échoue avec le motif \"QR Code malformé\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Alors ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Scan d\'une URL valide vers un équipement absent du référentiel")]
        public async global::System.Threading.Tasks.Task ScanDuneURLValideVersUnEquipementAbsentDuReferentiel()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Scan d\'une URL valide vers un équipement absent du référentiel", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 26
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 27
        await testRunner.GivenAsync("un QR Code encodant l\'URL \"https://gmao.exemple.fr/assets/00000000-0000-0000-0000" +
                        "-000000000099\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Étant donné ");
#line hidden
#line 28
        await testRunner.WhenAsync("le technicien scanne le QR Code", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quand ");
#line hidden
#line 29
        await testRunner.ThenAsync("l\'interprétation échoue avec le motif \"Équipement inconnu\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Alors ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Scan du QR Code d\'un équipement déposé")]
        public async global::System.Threading.Tasks.Task ScanDuQRCodeDunEquipementDepose()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Scan du QR Code d\'un équipement déposé", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 31
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 32
        await testRunner.GivenAsync("un QR Code encodant l\'URL \"https://gmao.exemple.fr/assets/7c9e6679-7425-40de-944b" +
                        "-e07fc1f90ae7\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Étant donné ");
#line hidden
#line 33
        await testRunner.WhenAsync("le technicien scanne le QR Code", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quand ");
#line hidden
#line 34
        await testRunner.ThenAsync("l\'interprétation échoue avec le motif \"Équipement déposé\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Alors ");
#line hidden
#line 35
        await testRunner.AndAsync("l\'équipement identifié porte le tag \"ASC-B2-007\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Et ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Robustesse de l\'extraction d\'identifiant selon le format scanné")]
        [global::NUnit.Framework.TestCaseAttribute("https://gmao.exemple.fr/assets/3f2504e0-4f89-41d3-9a0c-0305e82c3301", "Résolu", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("https://gmao.exemple.fr/assets/", "QR Code malformé", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("https://gmao.exemple.fr/3f2504e0-4f89-41d3-9a0c-0305e82c3301", "QR Code malformé", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("ftp://gmao.exemple.fr/assets/3f2504e0-4f89-41d3-9a0c-0305e82c3301", "QR Code malformé", "7", null)]
        [global::NUnit.Framework.TestCaseAttribute("", "QR Code malformé", "8", null)]
        public async global::System.Threading.Tasks.Task RobustesseDeLextractionDidentifiantSelonLeFormatScanne(string contenu, string motif, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("contenu", contenu);
            argumentsOfScenario.Add("motif", motif);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Robustesse de l\'extraction d\'identifiant selon le format scanné", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 38
        await testRunner.GivenAsync(string.Format("un QR Code encodant l\'URL \"{0}\"", contenu), ((string)(null)), ((global::Reqnroll.Table)(null)), "Étant donné ");
#line hidden
#line 39
        await testRunner.WhenAsync("le technicien scanne le QR Code", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quand ");
#line hidden
#line 40
        await testRunner.ThenAsync(string.Format("l\'interprétation aboutit au motif \"{0}\"", motif), ((string)(null)), ((global::Reqnroll.Table)(null)), "Alors ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
